#!/bin/bash

#export CFLAGS="-lwolfssl"
#export CC="clang"
#export CFLAGS='-fsanitize=memory'

if [ $# -eq 1 ]; then
  bld=$1
else
  bld="normal"
fi

echo "build: $bld"

cd src

if [ -f configure ]; then
  echo "build: rm configure"
  rm configure
fi

autoreconf || exit 1

#    --enable-debug \
#    --with-liblms=/home/jordan/work/cisco/lms/src/ \
#    --with-liblms=/usr/local/ \
if [[ $bld == "normal" ]]; then
  # build against hash-sigs LMS lib.
  ./configure \
    --enable-lms=yes \
    --with-liblms=yes \
    || exit 1

  make || exit 1
  sudo make install || exit 1
elif [[ $bld == "static" ]]; then
  # build against hash-sigs LMS lib.
  ./configure \
    --enable-static \
    --disable-shared \
    --enable-lms=yes \
    --with-liblms=/home/jordan/work/cisco/lms/src \
    || exit 1

  make || exit 1
else
  # build against wolfcrypt LMS.
  ./configure \
    --enable-lms=wolfssl \
    || exit 1
  make || exit 1
fi


